services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      EMAIL_ACCOUNT: ${EMAIL_ACCOUNT}
      APP_PASSWORD: ${APP_PASSWORD}

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      VITE_API_URL: "http://api:8080"
